backend:
  name: git-gateway
  branch: master
local_backend:
  url: http://localhost:8076/api/v1

media_folder: "media" # Media files will be stored in the repo under images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "updates" # Used in routes, e.g., /admin/collections/blog
    label: "Updates" # Used in the UI
    folder: "_updates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-update" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - label: Language
        name: language
        widget: relation
        collection: languages
        searchFields: ["language"]
        valueField: code
        displayFields: ["language"]
        default: "en"
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "guidelines" # Used in routes, e.g., /admin/collections/blog
    label: "Guidelines" # Used in the UI
    folder: "guidelines" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - label: Language
        name: language
        widget: relation
        collection: languages
        searchFields: ["language"]
        valueField: code
        displayFields: ["language"]
        default: "en"
      - { label: "Layout", name: "layout", widget: "hidden", default: "update" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Guidelines",
          name: "section",
          widget: "hidden",
          default: "guidelines",
        }
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ" # Used in the UI
    folder: "_faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - label: Language
        name: language
        widget: relation
        collection: languages
        searchFields: ["language"]
        valueField: code
        displayFields: ["language"]
        default: "en"
      - { label: "Section", name: "faq", widget: "hidden", default: "faq" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Answer", name: "body", widget: "markdown" }
  - name: "About"
    label: "about"
    editor:
      preview: false
    folder: "_about"
    create: true
    slug: "{{language}}"
    fields:
      - {
          label: Language,
          name: language,
          widget: relation,
          collection: languages,
          searchFields: ["language"],
          valueField: code,
          displayFields: ["language"],
          default: "en",
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          default: "About us",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "daily-stats"
    label: "Daily stats"
    editor:
      preview: false
    files:
      - label: "Daily-stats"
        name: "daily-stats"
        file: "_data/daily-stats.yml"
        fields:
          - { label: "Date", name: "dateUpdate" , default: "1 January 2020"}
          - { label: "Cases", name: "cases" , default: "0"}
          - { label: "Deaths", name: "deaths" , default: "0"}
          - label: Countries
            name: countries
            allow_add: false
            widget: list
            fields:
              - {label: Country, name: name, widget: string }
              - {label: Cases, name: cases, widget: string }
  - label: "Languages"
    name: "languages"
    folder: "_data/languages"
    extension: "yml"
    format: "yml"
    create: false
    slug: "{{code}}"
    editor:
      preview: false
    fields:
      - { label: "Language", name: "language" , widget: string}
      - { label: "Country Code (for url)", name: "code" , widget: string}
